language: java
dist: xenial
services: mysql
before_install:
  - mysql -e 'CREATE USER admin@localhost IDENTIFIED BY \'4dm1n\';'
  - mysql -e 'GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;'